name: brent-oil-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - statsmodels>=0.13.0
  - pymc3>=3.11.0
  - arviz>=0.12.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipykernel>=6.0.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - plotly>=5.0.0
  - dash>=2.0.0
  - dash-bootstrap-components>=1.0.0
  - flask>=2.0.0
  - requests>=2.25.0
  - python-dotenv>=0.19.0
  - pip
  - pip:
      - ruptures>=1.1.0
      - changepoint>=0.1.0
      - bokeh>=2.4.0
      - streamlit>=1.0.0
